In [7]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)
print(type(arr1))
print(arr1.shape)
arr1.reshape(1,10)

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
(10,)


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
#Attribute of numpy array
arr=np.array([[1,2,3],[4,5,6]])
print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of dimensions:",arr.ndim)
print("size:",arr.size)
print("DataType",arr.dtype)
print("item size:",arr.itemsize)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
size: 6
DataType int32
item size: 4


In [3]:
#Numpy vectorized operation
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])
print("Addition:",arr1+arr2)
print("Subtraction:",arr1-arr2)
print("Product:",arr1*arr2)
print("Division:",arr1/arr2)

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Product: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [4]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:",arr)

Array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
arr[0][0]

1

In [9]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [10]:
arr[0:2,2:]

array([[3, 4],
       [7, 8]])

In [12]:
arr[1:]=100
print(arr)

[[  1   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [16]:
#Statistical Concepts-Normalization
data=np.array([1,2,3,4,5])

mean=np.mean(data)
std=np.std(data)

normalized_data=(data-mean)/std
print("Normalized data:",normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [18]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

mean=np.mean(data)
print("Mean:",mean)

median=np.median(data)
print("Median:",median)

std=np.std(data)
print("Standard Deviation:",std)

variance=np.var(data)
print("Variance:",variance)


Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [22]:
#logical Operation
data=np.array([1,2,3,4,5,6,7,8,9,10])
data[data>5]

array([ 6,  7,  8,  9, 10])

In [28]:
data=np.array([1,2,3,4,5,6,7,8])
data[(data>3) & (data<=7)]

array([4, 5, 6, 7])